using System.Collections.Generic;

namespace WmiFileBrowser.Auxiliary
{
    static class ObjectInfoProvider
    {
        public static readonly Dictionary<ObjectType, ObjectInfoContainer> FullObjectInfo =
            new Dictionary<ObjectType, ObjectInfoContainer>
            {
                {
                    ObjectType.File, new ObjectInfoContainer(ObjectType.File, "cim_datafile", new[]
                    {
                        "AccessMask",
                        "Archive",
                        "Caption",
                        "Compressed",
                        "CompressionMethod",
                        "CreationClassName",
                        "CreationDate",
                        "CSCreationClassName",
                        "CSName",
                        "Description",
                        "Drive",
                        "EightDotThreeFileName",
                        "Encrypted",
                        "EncryptionMethod",
                        "Extension",
                        "FileName",
                        "FileSize",
                        "FileType",
                        "FSCreationClassName",
                        "FSName",
                        "Hidden",
                        "InstallDate",
                        "InUseCount",
                        "LastAccessed",
                        "LastModified",
                        "Manufacturer",
                        "Name",
                        "Path",
                        "Readable",
                        "Status",
                        "System",
                        "Version",
                        "Writeable"
                    })
                },
                {
                    ObjectType.Directory, new ObjectInfoContainer(ObjectType.Directory, "win32_directory", new[]
                    {
                        "AccessMask",
                        "Archive",
                        "Caption",
                        "Compressed",
                        "CompressionMethod",
                        "CreationClassName",
                        "CreationDate",
                        "CSCreationClassName",
                        "CSName",
                        "Description",
                        "Drive",
                        "EightDotThreeFileName",
                        "Encrypted",
                        "EncryptionMethod",
                        "Extension",
                        "FileName",
                        "FileSize",
                        "FileType",
                        "FSCreationClassName",
                        "FSName",
                        "Hidden",
                        "InstallDate",
                        "InUseCount",
                        "LastAccessed",
                        "LastModified",
                        "Name",
                        "Path",
                        "Readable",
                        "Status",
                        "System",
                        "Writeable"
                    })
                },
                {
                    ObjectType.Drive, new ObjectInfoContainer(ObjectType.Drive, "win32_volume", new[]
                    {
                        "Access",
                        "Automount",
                        "Availability",
                        "BlockSize",
                        "BootVolume",
                        "Capacity",
                        "Caption",
                        "Compressed",
                        "ConfigManagerErrorCode",
                        "ConfigManagerUserConfig",
                        "CreationClassName",
                        "Description",
                        "DeviceID",
                        "DirtyBitSet",
                        "DriveLetter",
                        "DriveType",
                        "ErrorCleared",
                        "ErrorDescription",
                        "ErrorMethodology",
                        "FileSystem",
                        "FreeSpace",
                        "IndexingEnabled",
                        "InstallDate",
                        "Label",
                        "LastErrorCode",
                        "MaximumFileNameLength",
                        "Name",
                        "NumberOfBlocks",
                        "PageFilePresent",
                        "PNPDeviceID",
                        "PowerManagementCapabilities",
                        "PowerManagementSupported",
                        "Purpose",
                        "QuotasEnabled",
                        "QuotasIncomplete",
                        "QuotasRebuilding",
                        "SerialNumber",
                        "Status",
                        "StatusInfo",
                        "SupportsDiskQuotas",
                        "SupportsFileBasedCompression",
                        "SystemCreationClassName",
                        "SystemName",
                        "SystemVolume"
                    })
                }
            };

        public static readonly Dictionary<ObjectType, ObjectInfoContainer> ShortObjectInfo =
            new Dictionary<ObjectType, ObjectInfoContainer>
            {
                {
                    ObjectType.File, new ObjectInfoContainer(ObjectType.File, "cim_datafile", new[]
                    {
                        "CreationDate",
                        "Drive",
                        "EightDotThreeFileName",
                        "Extension",
                        "FileName",
                        "FileSize",
                        "FileType",
                        "Hidden",
                        "LastAccessed",
                        "LastModified",
                        "Name",
                        "Path",
                        "Readable",
                        "System",
                        "Writeable"
                    })
                },
                {
                    ObjectType.Directory, new ObjectInfoContainer(ObjectType.Directory, "win32_directory", new[]
                    {
                        "CreationDate",
                        "Drive",
                        "EightDotThreeFileName",
                        "FileName",
                        "Hidden",
                        "LastModified",
                        "Name",
                        "Path",
                        "Readable",
                        "System",
                        "Writeable"
                    })
                },
                {
                    ObjectType.Drive, new ObjectInfoContainer(ObjectType.Drive, "win32_volume", new[]
                    {
                        "BlockSize",
                        "BootVolume",
                        "Capacity",
                        "Compressed",
                        "DeviceID",
                        "DriveLetter",
                        "DriveType",
                        "FileSystem",
                        "FreeSpace",
                        "Label",
                        "Name",
                        "SerialNumber"
                    })
                }
            };
    }
}
